### PR TITLE
fix(suppression.py) use python source default encoding

### PR DESCRIPTION
**Pull request by pahaz**
This is hotfix, more good solution is detect encoding before opening.

### CODE REVIEW

**Comment by pahaz** [comment]
More correct solution:

    def detect_encoding(b_lines):
        head = b''.join(b_lines[:2])
        m = re.search(b"coding[:=]\\s*([-\\w.]+)", head)
        return m.group(1).decode() if m else 'utf-8'

**Comment by pahaz** [comment]
Is this going to be merged?

**Comment by carlio** [comment]
Absolutely, thanks for the PR. I'm on holiday right now but will try to find some time - the weekend at the latest!

**Comment by pahaz** [comment]
why no merged? `utf-8` is default python source encoding

**Comment by carlio** [comment]
I did the fix in a different way using some encoding detection from elsewhere - https://github.com/landscapeio/prospector/commit/59146dfd1ad1f746f50497591aaa87adcadc63c0#diff-c97e03d5fc0f580123e3f7fc9a3dd996R59

**Pull request closed without merging**
