### PR TITLE
Added vscode formater and updated docs.

### PR DESCRIPTION
**Pull request by lfrodrigues**
Added new vscode formater that will be used by prospector plugin in vscode python extension. 

Updated docs related to vscode and my old xunit formater

### CODE REVIEW

**Comment by carlio** [comment]
Cheers, will get this into next release once I'm done going through all the open issues :+1:

**Comment by carlio** [comment]
@lfrodrigues is this line correct?
```
            template = '%(line)s,%(character)s,%(code)s,%(code)s:%(source)s %(message)s'
```
It duplicates the code, so error messages end up like
```
1,0,unused-import,unused-import:pylint Unused defaultdict imported from collections
```
`unused-import` is in that line twice. I have no idea about vscode so dunno if that is correct or not.

**Comment by lfrodrigues** [comment]
I built the vscode for this also: DonJayamanne/pythonVSCode#130

It was designed like that because vscode expects to have: 
```
const REGEX = '(?<line>\\d+),(?<column>\\d+),(?<type>[\\w-]+),(?<code>[\\w-]+):(?<message>.*)\\r?(\\n|$)';
```
From what I understood type was not available in prospector so I coded it like this. Ideally in type we should output something like the "category" in pylint. Is there a simple way to get that?

**Comment by carlio** [comment]
@lfrodrigues there isn't really a "type" value from any of the tools, unfortunately. I suppose you could use the `source` value instead but if it's fine as it is I will leave it alone :)

**Pull request merged**
