### PR TITLE
Replaced deprecated find_pylintrc by find_default_config_files

### PR DESCRIPTION
**Pull request by perestoronin**
Replaced deprecated find_pylintrc by find_default_config_files

PS. inpired by https://github.com/spyder-ide/spyder/pull/21470/files

## Description

patch error cannot import name 'find_pylintrc' from 'pylint.config' for latest pylint 3.0.2

## Related Issue

https://github.com/pylint-dev/pylint/issues/9105

## Motivation and Context

To work prospector with last pylint 3.0.2

## How Has This Been Tested?

run prospector --help with latest pylint 3.0.2 without error about 

```bash
File "/usr/lib/python3.11/site-packages/prospector/tools/pylint/__init__.py", line 8, in <module>
    from pylint.config import find_pylintrc
ImportError: cannot import name 'find_pylintrc' from 'pylint.config' (/usr/lib/python3.11/site-packages/pylint/config/__init__.py)
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM

**Comment by nfelt14** [comment]
@Pierre-Sassoulas, what will it take to get this merged and released?

**Comment by carlio** [comment]
It will take me pulling my finger out my arse.

Sorry for being absent. I'll do my best to get on this on Monday.

**Comment by nfelt14** [comment]
> It will take me pulling my finger out my arse.
> 
> Sorry for being absent. I'll do my best to get on this on Monday.

Just following up on this, any updates?

**Comment by nfelt14** [comment]
> It will take me pulling my finger out my arse.
> 
> Sorry for being absent. I'll do my best to get on this on Monday.

Any new updates?

**Comment by sbrunner** [comment]
Should we fork the project?

**Comment by carlio** [comment]
Sorry once again for being absent, real life got in the way and to be honest enthusiasm has died a bit. 

@sbrunner rather than fork, I'd suggest adding you and any others to the project as maintainers, if you would like. I'll still try to take part in maintenance. 

I'm also happy to move it out of this GitHub org, along with dependencies which are tied to it (like requirements-detector).

**Pull request merged**
